---
title: "VUW Psych 447: Methods"
author:
  - name: Joseph Bulbulia
    url: https://josephbulbulia.netlify.app
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: 0000-0002-5861-2056
  - name: Johannes Karl 
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: 0000-0001-5166-0728
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Class times and locations
**Lectures**
Tuesdays: 4:10 - 5:00 pm
Room: EA402  

**Workshops**
Wednesdays: 3:30 -- 5:20 PM

## Names and contact details

Lecturer & course coordinator: Prof. Joseph Bulbulia 
Email: joseph.bulbulia@vuw.ac.nz 

Lecturer & workshop coordinator: Johannes Karl
Email: johannes.karl@vuw.ac.nz


## Learning objectives

This course offers a gentle introduction to the R statistical programming language with practical applications for psychological science. We start with basic coding and workflow protocols, data wrangling and visualisation, and elementary regression, and gradually progress to more complex multilevel models.  The practical skills you acquire will prepare you for advanced research in psychological science  as well as for work in other areas of science, government, and industry. No prior familiarity with R or computer programming is required. 


## Where to find material

Weekly lectures and course resources are located [here](https://go-bayes.github.io/psych-423/)

Weekly problem sets are located [here](https://go-bayes.github.io/psych-423/assessments.html)

Any readings will be linked at to the lecture link. If there are no readings that week we will specify: **no readings**


## Assements 

1. **Weekly journal entries** (about 100 - 200 words) 
(10 X journals = **10%**)

These are **due every Friday** during term at midnight. Ordinarily we expect you to submit these on your GitHub page, however, we can make special accommodation for those who prefer VUW blackboard (see us).

Format: you will document your insights, questions, and frustrations in a weekly journal.  This record should include how you have sought help to address your questions, and how you have offered help. The purpose of the journals are to cultivate skills for interacting with the R community, and for documenting the research process. 
  
2. **Weekly workbook problem sets** 

You will find the problem sets [Here](https://go-bayes.github.io/psych-447/assessments.html). 
(10 x problem sets **= 50%**)

These are **due every Friday** during term at midnight. Ordinarily we expect you to submit these on your GitHub page, however, we can make special accommodation for those who prefer VUW blackboard (see us).


3. **Final project** consisting of:

  - 1 x short report of an analysis of a research question using a dataset (problem and dataset to be developed with your instructors by March 30th): 20%
  - 1 x 7-minute class presentation of your report: 10%
  - 1 x github website profiling your CV: 10%
  
  **= 40%**

The final project will be due 31st May 2021. Eventually, you will find materials to help you with you final project here [TBA](). 

## Communication of additional information and submissions

Lectures will be posted to: https://go-bayes.github.io/psych-423/

Course-related notices will appear on VUW Blackboard

Any information relating to Psyc 447or any last-minute changes to the course will be posted on Blackboard. 

Written work will be submitted via Github, unless otherwise specified.

The written components of the final project is **due every Friday** during term at midnight.

## Important dates

Trimester dates: 22 February to 20 June
Teaching dates: 22 February to 28 May

Mid-trimester break: 5 April to 18 April

Last assessment item due: Final assessment (project) will need to be submitted on 31st May (see [Assessments](https://go-bayes.github.io/psych-423/assessments.html))

Study Examination/Assessment Period: 
Note: students who enrol in courses with examinations must be able to attend an examination at the University at any time during the scheduled examination period.
Withdrawal dates: Refer to [Withdrawing](www.victoria.ac.nz/home/admisenrol/payments/withdrawalsrefunds)
If you cannot complete an assignment or sit a test or examination (aegrotats), refer to [Aegrotats](www.victoria.ac.nz/home/study/exams-and-assessments/aegrotat)

## Teaching format

Psyc 447 is a 15pt course which represents approx. 150 hours of total work for an average student.

In-class time involves (approx. 22hrs):

  1. Lectures by academic staff: Lectures will introducing the topics. These will be based on weekly readings.

  2. Class participation: you need to follow the lectures or else you will risk falling behind.
  
  3. Workshops: the weekly workshops are where you will receive hands on training. Again, you need to attend or follow these or else you will risk falling behind. 



## This course will demand 128hrs outside of lecture/workshops:

1.	Reading articles, (curated) R websites, and (curated) statistics websites  before & following class.
2.	Journal entries x 10 
3.  Problem sets/workbooks x 10
4.	Final project x 1 (including class presentation)


## Mandatory course requirements 

There are no mandatory course requirements.

## Workload

Given that Psyc 447 is a 15 point course, the expected workload is no less than 150 hours in total. This would mean roughly 15 hours per week. This should be viewed as a minimum - how much you get out of this course will depend on the work you put in.

## Penalties

Students must turn in all assignments on time by due dates. If students do not turn in an essay or assignment at a designated time, they will receive a zero for assignment this will be counted toward the final grade. 

## Materials and equipment and/or additional expenses

**Computer** 
a personal computer will be essential for completing this course. If you do not have access to a personal computer let your instructor know as soon as possible. 

**A github education account** 
This will be useful, even if not strictly necessary (i.e. you can set up an ordinary github account)

You should apply for a github education account as soon as possible here:
https://education.github.com/pack/offers



## Recommended reading 

Most of the material students will be expected to read is published in journals academic websites and, in some cases, in books. Students will generally need to read between one and five articles per week. Set readings will mostly be supplied throughout the course (please check this website). However, students will also be required to conduct their own independent reviews of the literature for assignment purposes.

## Other important information

The information above is specific to this course.  There is other important information that students must familiarise themselves with, including:

  - [Academic Integrity/Plagiarism](https://www.wgtn.ac.nz/students/support/student-interest-and-conflict-resolution/academic-integrity)
  
  - [Academic Progress](https://www.victoria.ac.nz/students/study/progress/academic-progess)
  
  - [Dates and deadlines](https://www.victoria.ac.nz/students/study/dates) 
  
  - [Faculty of Science Student and Academic Services Office](https://www.victoria.ac.nz/science/student-administration) 
  
  - [Grades](https://www.victoria.ac.nz/students/study/progress/grades) 
  
  - Special passes Refer to the [Assessment Handbook](https://www.victoria.ac.nz/documents/policy/staff-policy/assessment-handbook.pdf) 
  - [Statutes and policies](https://www.victoria.ac.nz/about/governance/strategy)
  
  - [Student support](https://www.victoria.ac.nz/students/support)
  
  - [Students with disabilities](https://www.victoria.ac.nz/st_services/disability/) 
  
  - [Student Charter](https://www.wgtn.ac.nz/learning-teaching/partnership/student-charter) 
  
  - [Terms and Conditions](https://www.wgtn.ac.nz/study/apply-enrol/terms-conditions/student-contract) 
  
  - [Turnitin](https://www.cad.vuw.ac.nz/wiki/index.php/Turnitin) 
  
  - [University structure](https://www.victoria.ac.nz/about/governance/structure) 
  
  - [VUWSA](https://www.vuwsa.org.nz)
  

## What do you need to do?

###  Attend Lectures 

Lecture dates are:

  - FEB 23
  - MAR 2
  - MAR 9
  - MAR 16
  - MAR 23
  - MAR 30
  - BREAK
  - APRI 20
  - APRIL 27
  - MAY 4
  - MAY 11
  - MAY 18: Presentations
  - MAY 25: Presentations

### Attend Weekly Workshops

There will be a  1.5-hour practicum each week in which students cultivate their skills by applying what the learn to data.  Learning applied statistics in R is like learning a language. Progress comes from immersing yourself in the language. You need to speak often, and you need to make lots of mistakes.  The weekly workshops will provide you with opportunity to *do R*.  The workshops will consist of your weekly problem sets + additional support. The are the place were we will help you individually and in groups, and were you will help each other. 

The weekly labs on the *Wednesdays* after the *Tuesday* lectures.

Workshop dates:

  - FEB 24
  - MAR 3
  - MAR 10
  - MAR 17
  - MAR 24
  - MAR 31
  - BREAK
  - APRI 21
  - APRIL 28
  - MAY 5
  - MAY 12
  - MAY 19: (focus on your project)
  - MAY 25: (focus on your project)


### Complete weekly "workbooks" 

Weekly assignments allow you to further develop you skills, and to build the statistical intuitions that will enable them to flexibly address a broad range of scientific problems. 

The focus of these assignments will be on *thinking* about coding and statistics, documenting *requests* for help, and *offers* for help. 


### Project

The course culminates with an in-depth project in which students work on data from their own area of interest combining R with contemporary tools of collaborative (GitHub) and open science (OSF). Student presentations will afford students with the opportunity to present their projects and offer each other constructive feedback.


## Outline


### Week 1 (a): Introduction: R and you

  -	Who will benefit from this course?
  -	What is R? 
  -	Downloading R and Rstudio (what is the difference).
  - What is GitHub
  - Why do I need these tools? 

### Week 1 (b): R basics

  -	Using R as a calculator
  -	Creating (and saving) a project using Rstudio
  - Loading Data
  -	The basics of your workflow

### Week 1 (c): R Markdown
  -	The elements of Rmarkdown   
  -	Your first Rmarkdown document
  -	GitHub 
  -	Packages

### Week 2 (a): Data visualisation

  -	Data visualisation with ggplot2 
  -	Creating a graph
  -	Layers
  -	Facets
  -	Understanding your data through graphs…


[USEFUL](https://m-clark.github.io/exploratory-data-analysis-tools/)

### Week 2 (b): Coding basics

  -	Basic types  of data in R
    - Numbers and integers 
  -	Factors (ordered, unordered)
  -	Characters
  -	Lists, Arrays, Matrices & data frames
  -	Assignment 
    - Functions
    - Coding etiquette… etc 

### Week 3 (a): Data transformation

  -	Pipe operators
  -	Select, filter, operators, missing values, arrange.
  -	Mutate & data transformation
  -	Tidy data

### Week 3 (b):  Rolling your own functions: when, why, and how


### Week 4: CONSOLODATION OF SKILLS IN R 

### Week 5 (a):  Samples and parameters: observation and inference

### Week 5 (b): Linear and non-linear relationships with one co-variate

### Week 6 (a): Two covariates & the spectre of confounding

### Week 6 (b): An introduction to causal DAGS (using ggdag) 

### Week 7 (a): Modelling binary data  

### Week 7 (b): Modelling count data + zero inflation

### Week 8 (a): Introduction to multilevel models: group-level intercepts 

### Week 8 (b): Introduction to multilevel models: group-level slopes

### Week 9 (a): Multivariate multilevel regression.

### Week 9 (b): Longitudinal inference: within and between-individual effects, the when and when-not of mediation.

### Week 10 (a): Missing data and other measurement opportunities.

### Week 10 (b):  CONSOLIDATION OF STATISTICS

### Week 11: Student presentations of projects: using Rstudio & GitHub/OSF

### Week 12:  Student presentations of projects: using Rstudio & GitHub/OSF



## Acknowledgments

  -  Some code used in creating this course website comes from: Matti Vuorre (former VUW psych student): https://vuorre.netlify.app/
  -  Statistical approaches: Richard McElreath's Statistical Rethinking: https://github.com/rmcelreath/stat_rethinking_2020 

