---
title: "VUW Psych 447: Statistics for Psychological Science in R"
author:
  - name: Joseph Bulbulia
    url: https://josephbulbulia.netlify.app
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: 0000-0002-5861-2056
bibliography: bibliography.bib
output:
  distill::distill_article:
    self_contained: false
    toc: true
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## What to submit? 

###  **Weekly journal entries** (about 100 - 200 words) 
(10 X journals = **10%**)

These are **due every Tuesday ** during term one week after the class in which the assignment was given.

Format: you will document your insights, questions, and frustrations in a weekly journal.  This record should include how you have sought help to address your questions, and how you have offered help. The purpose of the journals are to cultivate skills for interacting with the R community, and for documenting the research process. 
  
### **Weekly workbook problem sets** 

Weekly workbooks are [here](https://go-bayes.github.io/psych-447/index_workbooks.html)
(10 x problem sets **= 50%**)

We will have 12 workbooks, but you will only be marked on your best 10. You may therefore skip 2 x workbooks. You also may due 11 or 12 workbooks, but only the top 10 will count. 

Problem sets are also **due every Tuesday** during term before the following week's class or in the case of the final week, on 1 June 2021 (see the workbook submission schedule below).

### Final report consisting of:

  - 1 x short article (2500 word max): project due May 31 2021: 35%
  - 1 x GitHub website profiling your CV: project CV due May 31 2021: 5%
  - **Note** we require your project idea by the lab meeting on 31 March 2021.
  
  **= 40%**

## Due dates for journals:

  - Week 1: Due FRIDAY 27th February
  - Week 2: FRIDAY Due March 5th
  - Week 3: FRIDAY Due March 12th
  - Week 4: FRIDAY Due March 19th
  - Week 5: FRIDAY Due March 26th
  - Week 6: FRIDAY Due April 2nd
  - Week 7: FRIDAY Due April 23rd
  - Week 8: FRIDAY April 30th
  - Week 9: FRIDAY May 7th
  - Week 10: FRIDAY May 14th
  - Week 11: FRIDAY May 21st
  - Week 12: FRIDAY Due May 28th


## Due dates for problem sets


One week after the relevant lecture, hence:

  - Week 1 workbook due: MAR 2
  - Week 2 workbook due: MAR 9
  - Week 3 workbook due: MAR 16
  - Week 4 workbook due: MAR 23
  - Week 5 workbook due: MAR 30
  BREAK
  - Week 6 workbook due: APRI 20
  - Week 7 workbook due: APRIL 27
  - Week 8 workbook due: MAY 4
  - Week 9 workbook due: MAY 11
  - Week 10 workbook due: MAY 18 
  - Week 11 workbook due: MAY 25
  - Week 12 workbook due: JUNE 1st

## Due date for final project

Monday May 31st

## Due date for GitHub CV

Monday May 31st


## Assessment criteria

### Assessment criteria for weekly journals

The purpose of the journal is to provide evidence of course engagement: 

- did the student attempt to learn the material for the week? 
- did the student seek help when help was needed?  
- did the student offer help? 
- did the student’s engagement exhibit
  + rigour?
  + determination?
  + originality?

### Assessment criteria for workbooks


#### Rigour

- Are the answers correct?
- Did the student comment on all code? 
- Is the work reproducible? 
- Did the student the student accurately record the process of data analysis, including sources for the approach? 

#### Clarity

- Are the comments and text clearly written and easy to follow? 
- Is the document well organised? 

#### Creativity 

- Did the student show evidence for clarity, creativity, and rigour, and thoughtfulness in reasoning about the approach? 
- Did the student seek and offer help?  
- If so, did the student seek and offer help effectively? 


### Assessment criteria for the final report

#### Rigour

- Did the student comment on all code? 
- Is the work reproducible? 
- Did the student the student accurately record the process of data analysis, including sources for the approach? 
- Is the report accessible on GitHub, and where relevant OSF? 
- Does the GitHub/OSF workflow exhibit order and clarity? 
- Are the graphs appropriate, clear, and helpful in understanding the results? 

#### Clarity

- Are the comments in the analysis clearly written and easy to follow?
- Is the analysis reproducible? 
- Is the report clearly written and easy to follow? 
- Does the document structure guide the reader’s understanding of the analysis and inference? 

#### Creativity 

- Does the approach in the analysis reflect mastery of the analytic procedures covered in this course
- Does the analysis reflect mastery of the graphical and analytic methods taught in this course?
- Are the conclusions well-supported and correct? 
- Does the report describe future pathways for research. 


### Assessment criteria for the GitHub CV

#### Rigour

- Is the GitHub repository for the webpage efficiently structured? 
- Does the wepage work? 
- Is all code commented? 

#### Clarity

- Is the webpage page easy to navigate
- Is the webage overly cluttered? 

#### Creativity 

- Is the CV page easy to read?  
- Does the webpage contain an academic CV? 
- Does the webpage contain a student’s education, skills, and training? 
- Does the webpage convey the student's professional qualities, research, and skills?
- Does the webpage make effective use of data visualisation and images? 

## Where to submit?

All assessments to be submitted on Blackboard

### Weekly journals

- as .Rmd files *and* as .doc or .pdf files (.docx,  .rtf  and .txt = OK too)

### Weekly workboks

- as .Rmd files *and* as .doc or .pdf files (.docx,  .rtf  and .txt = OK too)


### Final report

- as .doc or .pdf files (.docx,  .rtf  and .txt = OK too)

### GitHub CV

- as a link to your webpage. 


