---
title: 'VUW Psych 447: Methods in R'
site: distill::distill_website
listing:
  posts:
  - 1_1
  - 2_1
  - 3_1
  - 4_1
  - 5_1
  - 6__1
  - 7_1
  - 8_1
  - 9_1
  - 10_1
  - 11_1
  - 12_1
  workbooks:
  - W_1
  - W_2_s
  - W_3_s
  - W_4_s
  - W_5_s
  - W_6_s
  - W_7_s
  - W_8_s
  - W_9_s
  - W_10_s
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include = FALSE}
library(here)
# GitHub pages
file.create("docs/.nojekyll", showWarnings = FALSE)
# Ensure directories exist
dir.create("data", FALSE)
dir.create("models", FALSE)
```

```{r render-everything, include = FALSE, eval = FALSE}
# Use to render all posts (article and slide deck) if needed
library(rmarkdown)
posts <- list.files(
  "_posts", recursive = TRUE, pattern = ".Rmd", full.names = TRUE
  )
purrr::walk(posts, render)

labs <- list.files(
  "_labs", recursive = TRUE, pattern = ".Rmd", full.names = TRUE
  )
purrr::walk(labs, render)

workbooks <- list.files(
  "_workbooks", recursive = TRUE, pattern = ".Rmd", full.names = TRUE
  )
purrr::walk(workbooks, render)
```

