---
title: "Week 1 Workbook"
description: |
author:
  - name: Joseph Bulbulia
    url: https://josephbulbulia.netlify.app
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: 0000-0002-5861-2056
output:
  distill::distill_article:
    self_contained: false
    toc: true
---


### Task 1 Apply for a github education account

-   apply here: <https://education.github.com/pack/offers>
-   set up a github account.
-   choose a username that will be OK for professional purposes (e.g. your name)

### Task 2 Download R for free here:

<https://www.r-project.org>

### Task 3 Download Rstudio for free here:

<https://rstudio.com/products/rstudio/download/#download>

Update R and Rstudio to the latest versions. Don't worry if you have problems, we'll be working through your problems in the first week, and throughout the course. We assume no prior experience with R or Git/GitHub

### Task 4 Create your first repository

### Task 5 Commit your first Rmarkdown journal

-   Create your first Rmarkdown document, and title it "My Journal"
-   Record your impressions of the process of getting set up with RStudio and GitHub
-   **Record any help you have offered to other people,** and any help you have sought from other people, along the way.
-   Save the document and commit it to GitHub.
-   Note: set your github repository to private if you wish the account to be private

### Grading points

-   Your Rmarkdown document must include each of the following

1.  

    > ## Heading

2.  

    > ~~crossed out text~~

3.  

    > link to a [website](https://www.theonion.com/)

4.  

    > A footnote [^1]

5.  

    > An inspirational quote

6.  

    > BONUS: figure out how to add a bibliographic citation, such as [@darwin1964origin]
    
7.  
   > A record of help you sought and offered. 

[^1]: Humanities scholars love footnotes.

### Submit a link to your journal on Blackboard.

Blackboard isn't our favourite tool, however, we need to respect the norms of our community. For this reason, presently all of your assessments need to be uploaded through Blackboard. 

-   On Blackboard, pass us a link to your GitHub document on Blackboard for weekly assessments
-   This journal will count as both your weekly journal entry and your weekly workbook -- double credits!
